name: Working Dirs & Shells
on: [push]
defaults:
  run:
    shell: bash

jobs:
  display-ubuntu-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working dir
        working-directory: ${{ github.workspace }}
        run: |
          pwd
  display-wd-info:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Display Working Directory & List Files
        run: |
          Get-Location
          dir
          echo $env::$GITHUB_SHA
          echo $env::$GITHUB_REPOSITORY
          echo $env::$GITHUB_WORKSPACE
