name: Events workflow
on:
  push:
  pull_request:
    types: [opened, assigned, reopened]

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - name: some echo
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo "Test commit"
      - name: Checkout test
        uses: actions/checkout@v4
